// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pdb014App.Repository;

namespace Pdb014App.Repository.Migrations.UserDb
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("UserRoleList");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoleClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserToken");
                });

            modelBuilder.Entity("Pdb014App.Models.UserManage.LookUpUserActivationStatus", b =>
                {
                    b.Property<int>("UserActivationStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserActivationStatusId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserActivationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("UserActivationStatusId");

                    b.ToTable("UserActivationStatus");
                });

            modelBuilder.Entity("Pdb014App.Models.UserManage.LookUpUserBpdbDivision", b =>
                {
                    b.Property<int>("BpdbDivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("BpdbDivisionId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BpdbDivisionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("BpdbDivisionId");

                    b.ToTable("UserBpdbDivision");
                });

            modelBuilder.Entity("Pdb014App.Models.UserManage.LookUpUserBpdbEmployee", b =>
                {
                    b.Property<int>("BpdbEmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("BpdbEmployeeId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BpdbDivisionId")
                        .HasColumnName("BpdbDivisionId")
                        .HasColumnType("int");

                    b.Property<string>("BpdbEmpDesignation")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("BpdbEmployeeLevel")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CircleCode")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("SnDCode")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("SubstationId")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("ZoneCode")
                        .HasColumnName("ZoneCode")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("BpdbEmployeeId");

                    b.HasIndex("BpdbDivisionId");

                    b.ToTable("UserBpdbEmployee");
                });

            modelBuilder.Entity("Pdb014App.Models.UserManage.LookUpUserContentType", b =>
                {
                    b.Property<int>("ContentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ContentTypeId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("ContentTypeId");

                    b.ToTable("UserContentType");
                });

            modelBuilder.Entity("Pdb014App.Models.UserManage.LookUpUserPermissionType", b =>
                {
                    b.Property<int>("PermissionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PermissionTypeId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PermissionTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("PermissionTypeId");

                    b.ToTable("UserPermissionType");
                });

            modelBuilder.Entity("Pdb014App.Models.UserManage.LookUpUserSecurityQuestion", b =>
                {
                    b.Property<int>("UserSecurityQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserSecurityQuestionId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserSecurityQuestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("UserSecurityQuestionId");

                    b.ToTable("UserSecurityQuestion");
                });

            modelBuilder.Entity("Pdb014App.Models.UserManage.LookUpUsersPermittedContent", b =>
                {
                    b.Property<int>("UsersPermittedContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UsersPermittedContentId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("ContentDescription")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("ContentName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("ContentTitle")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int?>("ContentTypeId")
                        .HasColumnName("ContentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ControllerName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("ModelName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("UsersPermittedContentId");

                    b.HasIndex("ContentTypeId");

                    b.ToTable("UsersPermittedContent");
                });

            modelBuilder.Entity("Pdb014App.Models.UserManage.TblUserGrpWisePermissionDetail", b =>
                {
                    b.Property<int>("PermissionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PermissionTypeId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnName("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.Property<int>("UsersPermittedContentId")
                        .HasColumnName("UsersPermittedContentId")
                        .HasColumnType("int");

                    b.HasKey("PermissionTypeId");

                    b.HasIndex("Id");

                    b.HasIndex("UsersPermittedContentId");

                    b.ToTable("UserGrpWisePermissionDetail");
                });

            modelBuilder.Entity("Pdb014App.Models.UserManage.TblUserGrpWiseUsersDistribution", b =>
                {
                    b.Property<int>("UserDistributionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserDistributionId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnName("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.Property<int>("UserId")
                        .HasColumnName("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserDistributionId");

                    b.HasIndex("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserGrpWiseUsersDistribution");
                });

            modelBuilder.Entity("Pdb014App.Models.UserManage.TblUserLogHistory", b =>
                {
                    b.Property<int>("UserLogHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserLogHistoryId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LogOutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoginNotes")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ServerOrIPAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("UserId")
                        .HasColumnName("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserLogHistoryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogHistory");
                });

            modelBuilder.Entity("Pdb014App.Models.UserManage.TblUserProfileDetail", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BpdbDivisionId")
                        .HasColumnName("BpdbDivisionId")
                        .HasColumnType("int");

                    b.Property<string>("BpdbEmpDesignation")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("BpdbEmployeeId")
                        .HasColumnName("BpdbEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("BpdbEmployeeLevel")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CircleCode")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnName("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.Property<bool>("IsBpdbEmployee")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProfileSubmitted")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityQuestionAnswer")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("SignatureFileName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("SnDCode")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("SubstationId")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UserAddress")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("UserAlternateEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAlternateMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UserDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserDesignation")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("UserFullName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("UserNID")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("UserProfession")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int?>("UserSecurityQuestionId")
                        .HasColumnName("UserSecurityQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("ZoneCode")
                        .HasColumnName("ZoneCode")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("UserId");

                    b.HasIndex("BpdbDivisionId");

                    b.HasIndex("BpdbEmployeeId");

                    b.HasIndex("Id");

                    b.HasIndex("UserSecurityQuestionId");

                    b.ToTable("UserProfileDetail");
                });

            modelBuilder.Entity("Pdb014App.Models.UserManage.TblUserRegistrationDetail", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<int?>("UserActivationStatusId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("UserNames")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("VerificationCode")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserActivationStatusId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Pdb014App.Models.UserManage.TblUserRegistrationDetail", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Pdb014App.Models.UserManage.TblUserRegistrationDetail", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pdb014App.Models.UserManage.TblUserRegistrationDetail", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Pdb014App.Models.UserManage.TblUserRegistrationDetail", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pdb014App.Models.UserManage.LookUpUserBpdbEmployee", b =>
                {
                    b.HasOne("Pdb014App.Models.UserManage.LookUpUserBpdbDivision", "UserBpdbEmployeeUserBpdbDivision")
                        .WithMany()
                        .HasForeignKey("BpdbDivisionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pdb014App.Models.UserManage.LookUpUsersPermittedContent", b =>
                {
                    b.HasOne("Pdb014App.Models.UserManage.LookUpUserContentType", "UsersPermittedContentToUserContentType")
                        .WithMany()
                        .HasForeignKey("ContentTypeId");
                });

            modelBuilder.Entity("Pdb014App.Models.UserManage.TblUserGrpWisePermissionDetail", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "UserGrpWisePermissionDetailToIdentityRole")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pdb014App.Models.UserManage.LookUpUsersPermittedContent", "UserGrpWisePermissionDetailToUsersPermittedContent")
                        .WithMany()
                        .HasForeignKey("UsersPermittedContentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pdb014App.Models.UserManage.TblUserGrpWiseUsersDistribution", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "UserGrpWiseUsersDistributionToIdentityRole")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pdb014App.Models.UserManage.TblUserProfileDetail", "UserGrpWiseUsersDistributionToUserProfileDetail")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pdb014App.Models.UserManage.TblUserLogHistory", b =>
                {
                    b.HasOne("Pdb014App.Models.UserManage.TblUserProfileDetail", "UserLogHistoryToUserProfileDetail")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pdb014App.Models.UserManage.TblUserProfileDetail", b =>
                {
                    b.HasOne("Pdb014App.Models.UserManage.LookUpUserBpdbDivision", "UserBpdbEmployeeUserBpdbDivision")
                        .WithMany()
                        .HasForeignKey("BpdbDivisionId");

                    b.HasOne("Pdb014App.Models.UserManage.LookUpUserBpdbEmployee", "UserProfileDetailToUserBpdbEmployee")
                        .WithMany()
                        .HasForeignKey("BpdbEmployeeId");

                    b.HasOne("Pdb014App.Models.UserManage.TblUserRegistrationDetail", "UserProfileDetailToUserRegistrationDetail")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pdb014App.Models.UserManage.LookUpUserSecurityQuestion", "UserSecurityQuestion")
                        .WithMany()
                        .HasForeignKey("UserSecurityQuestionId");
                });

            modelBuilder.Entity("Pdb014App.Models.UserManage.TblUserRegistrationDetail", b =>
                {
                    b.HasOne("Pdb014App.Models.UserManage.LookUpUserActivationStatus", "UserRegistrationDetailToUserActivationStatus")
                        .WithMany()
                        .HasForeignKey("UserActivationStatusId");
                });
#pragma warning restore 612, 618
        }
    }
}
